### ISSUE TITLE
Question: Different Configurations With FlexLayout

### ISSUE THREAD

**Issue by patchthecode** [lucdion/FlexLayout#27]
Hi, I was having trouble setting up  something like this:

<img width="250" alt="screen shot 2017-10-17 at 9 56 22 am" src="https://user-images.githubusercontent.com/2439146/31677977-796444c0-b321-11e7-8b4f-355807ee3f25.png">

I always seem to have the left text pushing the right text outside of the box (overflow?)
My code was basically this:
```swift
flex.addItem().direction(.row).define { flex in
   flex.addItem(text1)
   flex.addItem(text2)
}
```

I also tried different combinations of positioning, but without much luck. Any advice?

Edit - is there a way to maybe divide the flex box into percentage proportions?
link maybe this
<img width="254" alt="screen shot 2017-10-17 at 10 04 28 am" src="https://user-images.githubusercontent.com/2439146/31678302-9c2645f2-b322-11e7-883b-0bbfa4e9516d.png">

That way, i have multiple sections with different kinds of setup. I am not sure if you already have things that can accomplish this.

**Comment by lucdion** [comment]
Hi @patchthecode, this occurs because by default the shrink factor is 0, which means views size won't be adjusted to match the available container space. See https://github.com/lucdion/FlexLayout#shrink

To fix that you must set the shrink factor to at least one of your views.

Shrink is about proportions. If an item has a shrink of 3, and the other has a shrink of 1, the first item will shrink 3x as fast as the other.

This should fix your problem of overflow:

```
flex.addItem().direction(.row).define { flex in
   flex.addItem(text1).shrink(1)
   flex.addItem(text2).shrink(3)
}
```

Percent is not supported yet, but I plan to implement it very soon.

**Comment by patchthecode** [comment]
hmm. Ok there's something i do not seem to understand about this>
I'll create a sample project and link it here in a couple hours.

**Comment by lucdion** [comment]
I've added the possibility of specifying percentages for width, height, maxWidth, minWidth, maxHeight and minHeight.

https://github.com/lucdion/FlexLayout/releases/tag/1.1.4

**Comment by patchthecode** [comment]
awesome. Checking it out right now.

**Comment by patchthecode** [comment]
Percentage proportions make is so much easier than the shrink & grow for my use case.
Thanks man.
